[package]
authors = ["rohanbari <rohanbari4@gmail.com>"]
edition = "2018"
name = "rust-lang"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
